import { Task, Candidate, Interview, ActivityItem, ChatMessage } from '@/types';

export const INITIAL_TASKS: Task[] = [
  {
    id: 'TSK-101',
    title: "Screen Rahul Sharma's resume",
    description: 'Detailed analysis of Python, FastAPI, and async architecture experience against Job Spec.',
    candidateName: 'Rahul Sharma',
    candidateId: 'CAN-001',
    assignedTo: 'Virtual HR',
    priority: 'High',
    status: 'In Progress',
    dueDate: 'Today',
    progress: 75,
    createdAt: '2026-09-14 09:15',
  },
  {
    id: 'TSK-102',
    title: 'Schedule technical interview',
    description: 'Coordinate available time slot for technical assessment with Priya Mehta.',
    candidateName: 'Priya Mehta',
    candidateId: 'CAN-002',
    assignedTo: 'Virtual HR',
    priority: 'Medium',
    status: 'Pending',
    dueDate: 'Today',
    progress: 20,
    createdAt: '2026-09-14 09:45',
  },
  {
    id: 'TSK-103',
    title: 'Review candidate applications',
    description: 'Batch review of 12 inbound frontend developer portfolios and GitHub repositories.',
    candidateName: 'Multiple Candidates (12)',
    assignedTo: 'Virtual HR',
    priority: 'High',
    status: 'Completed',
    dueDate: 'Yesterday',
    progress: 100,
    createdAt: '2026-09-13 14:00',
  },
  {
    id: 'TSK-104',
    title: 'Generate candidate summary report',
    description: 'Compile AI benchmark scorecard and skill gap analysis for Senior Backend role.',
    candidateName: 'Vikram Malhotra',
    candidateId: 'CAN-003',
    assignedTo: 'Virtual HR',
    priority: 'Medium',
    status: 'In Progress',
    dueDate: 'Tomorrow',
    progress: 45,
    createdAt: '2026-09-14 10:10',
  },
  {
    id: 'TSK-105',
    title: 'Send interview confirmation email',
    description: 'Send calendar invite and preparatory guidelines for upcoming technical evaluation.',
    candidateName: 'Sneha Patel',
    candidateId: 'CAN-004',
    assignedTo: 'Virtual HR',
    priority: 'Low',
    status: 'Completed',
    dueDate: 'Sep 13',
    progress: 100,
    createdAt: '2026-09-13 16:30',
  },
  {
    id: 'TSK-106',
    title: 'Initial phone screening evaluation',
    description: 'Perform structured AI phone screening questionnaire focusing on communication and culture fit.',
    candidateName: 'Ananya Roy',
    candidateId: 'CAN-005',
    assignedTo: 'Virtual HR',
    priority: 'High',
    status: 'Pending',
    dueDate: 'Tomorrow',
    progress: 0,
    createdAt: '2026-09-14 10:30',
  },
];

export const INITIAL_CANDIDATES: Candidate[] = [
  {
    id: 'CAN-001',
    name: 'Rahul Sharma',
    email: 'rahul.sharma@example.com',
    phone: '+91 98765 43210',
    appliedFor: 'Python Developer',
    status: 'Interview',
    interviewStatus: 'Video scheduled for today at 11:00 AM',
    experience: '4.5 years',
    matchScore: 94,
    appliedDate: 'Sep 10, 2026',
    skills: ['Python', 'FastAPI', 'PostgreSQL', 'Docker', 'Redis', 'Microservices'],
    resumeSnippet:
      'Backend Engineer with 4.5+ years experience architecting distributed REST APIs and event-driven backends using Python, FastAPI, and SQLAlchemy. Reduced latency by 35% using caching and query optimization.',
    notes: 'Strong algorithmic background. Proven track record in scaling microservices. Recommended for Tech Round 1.',
    interviewHistory: [
      {
        id: 'INT-001',
        date: '2026-09-14 11:00',
        mode: 'Video',
        result: 'Confirmed - Scheduled with Tech Lead',
      },
    ],
  },
  {
    id: 'CAN-002',
    name: 'Priya Mehta',
    email: 'priya.mehta@example.com',
    phone: '+91 98123 45678',
    appliedFor: 'Data Analyst',
    status: 'Screening',
    interviewStatus: 'Chat interview scheduled for today at 03:30 PM',
    experience: '3 years',
    matchScore: 89,
    appliedDate: 'Sep 11, 2026',
    skills: ['SQL', 'Python', 'Power BI', 'Tableau', 'Pandas', 'ETL'],
    resumeSnippet:
      'Data Analyst skilled in translating complex business queries into actionable dashboards. Led cross-functional analytics projects reducing customer churn by 12%.',
    notes: 'Virtual HR verified SQL credentials and analytics portfolio. Ready for quick domain assessment.',
    interviewHistory: [
      {
        id: 'INT-002',
        date: '2026-09-14 15:30',
        mode: 'Chat',
        result: 'Scheduled - AI Domain Quiz',
      },
    ],
  },
  {
    id: 'CAN-003',
    name: 'Vikram Malhotra',
    email: 'vikram.m@example.com',
    phone: '+91 97654 32109',
    appliedFor: 'Senior Backend Engineer',
    status: 'Interview',
    interviewStatus: 'Completed Round 1, scheduling Round 2',
    experience: '7 years',
    matchScore: 96,
    appliedDate: 'Sep 08, 2026',
    skills: ['Go', 'Python', 'System Design', 'Kubernetes', 'MySQL', 'AWS'],
    resumeSnippet:
      'Senior Infrastructure & Backend Engineer with expertise in high-throughput transactional engines, cloud infrastructure, and low-latency databases.',
    notes: 'Exceptional system design feedback. Virtual HR flagged him in top 5% of candidate pool.',
    interviewHistory: [
      {
        id: 'INT-PREV',
        date: '2026-09-12 14:00',
        mode: 'Video',
        result: 'Passed - 9.2/10 rating',
      },
    ],
  },
  {
    id: 'CAN-004',
    name: 'Sneha Patel',
    email: 'sneha.patel@example.com',
    phone: '+91 99887 66554',
    appliedFor: 'HR Operations Specialist',
    status: 'Selected',
    interviewStatus: 'Offer extended',
    experience: '5 years',
    matchScore: 92,
    appliedDate: 'Sep 05, 2026',
    skills: ['HR Operations', 'Workday', 'Talent Acquisition', 'Payroll', 'Compliance'],
    resumeSnippet:
      'Experienced People Operations specialist managing onboarding, compensation, and global talent pipelines across 300+ employee organization.',
    notes: 'Outstanding references verified. Offer letter generated by Virtual HR.',
  },
  {
    id: 'CAN-005',
    name: 'Ananya Roy',
    email: 'ananya.roy@example.com',
    phone: '+91 98450 11223',
    appliedFor: 'Frontend Developer',
    status: 'New',
    interviewStatus: 'Screening in progress',
    experience: '2.5 years',
    matchScore: 84,
    appliedDate: 'Sep 13, 2026',
    skills: ['React', 'Next.js', 'TypeScript', 'Tailwind CSS', 'Redux', 'Jest'],
    resumeSnippet:
      'Frontend developer passionate about UI/UX performance, responsive components, and accessible design systems. Built high-traffic checkout flows.',
    notes: 'Portfolio inspected by Virtual HR. Good typography and component architecture skills.',
  },
  {
    id: 'CAN-006',
    name: 'Rohan Gupta',
    email: 'rohan.g@example.com',
    phone: '+91 97112 33445',
    appliedFor: 'DevOps Engineer',
    status: 'Rejected',
    interviewStatus: 'Feedback sent',
    experience: '1.5 years',
    matchScore: 68,
    appliedDate: 'Sep 09, 2026',
    skills: ['Linux', 'Docker', 'Git'],
    resumeSnippet: 'Junior systems administrator looking to transition into full-time DevOps & Cloud engineering.',
    notes: 'Position requires minimum 4 years Terraform & K8s production experience. Virtual HR sent polite rejection with feedback.',
  },
];

export const INITIAL_INTERVIEWS: Interview[] = [
  {
    id: 'INT-001',
    candidateId: 'CAN-001',
    candidateName: 'Rahul Sharma',
    position: 'Python Developer',
    date: 'Today',
    time: '11:00 AM',
    mode: 'Video',
    status: 'Confirmed',
    interviewer: 'Virtual HR + Lead Architect',
    notes: 'Focus on FastAPI performance, async queue patterns, and live coding.',
  },
  {
    id: 'INT-002',
    candidateId: 'CAN-002',
    candidateName: 'Priya Mehta',
    position: 'Data Analyst',
    date: 'Today',
    time: '03:30 PM',
    mode: 'Chat',
    status: 'Scheduled',
    interviewer: 'Virtual HR Assistant',
    notes: 'Automated 30-minute structured interactive technical Q&A session.',
  },
  {
    id: 'INT-003',
    candidateId: 'CAN-003',
    candidateName: 'Vikram Malhotra',
    position: 'Senior Backend Engineer',
    date: 'Tomorrow',
    time: '10:00 AM',
    mode: 'Video',
    status: 'Scheduled',
    interviewer: 'VP of Engineering',
    notes: 'System architecture deep-dive: Database sharding & concurrency.',
  },
  {
    id: 'INT-004',
    candidateId: 'CAN-005',
    candidateName: 'Ananya Roy',
    position: 'Frontend Developer',
    date: 'Sep 16, 2026',
    time: '02:00 PM',
    mode: 'Voice',
    status: 'Scheduled',
    interviewer: 'Virtual HR Screener',
    notes: 'Initial culture fit and conversational screening round.',
  },
  {
    id: 'INT-005',
    candidateId: 'CAN-004',
    candidateName: 'Sneha Patel',
    position: 'HR Operations Specialist',
    date: 'Yesterday',
    time: '04:00 PM',
    mode: 'Video',
    status: 'Completed',
    interviewer: 'CEO & Head of People',
    notes: 'Candidate passed all rounds. Offer finalized.',
  },
];

export const INITIAL_ACTIVITIES: ActivityItem[] = [
  {
    id: 'ACT-001',
    action: 'Interview scheduled',
    description: 'Rahul Sharma — Python Developer (Video Mode)',
    timestamp: '10:42 AM',
    type: 'interview',
    status: 'Confirmed',
  },
  {
    id: 'ACT-002',
    action: 'Task completed',
    description: 'Resume screening — Batch analysis completed for 12 applicants',
    timestamp: '10:25 AM',
    type: 'task',
    status: 'Completed',
  },
  {
    id: 'ACT-003',
    action: 'Task started',
    description: 'Candidate review & scorecard calculation for Senior Backend position',
    timestamp: '09:58 AM',
    type: 'ai',
    status: 'In Progress',
  },
  {
    id: 'ACT-004',
    action: 'Virtual HR updated task status',
    description: "Moved 'Screen Rahul Sharma's resume' to In Progress (75% completed)",
    timestamp: '09:30 AM',
    type: 'ai',
    status: 'Updated',
  },
  {
    id: 'ACT-005',
    action: 'Candidate added',
    description: 'Ananya Roy applied for Frontend Developer',
    timestamp: '09:05 AM',
    type: 'candidate',
    status: 'New',
  },
  {
    id: 'ACT-006',
    action: 'Task assigned to Virtual HR',
    description: "Assigned 'Schedule technical interview' for Priya Mehta",
    timestamp: '08:45 AM',
    type: 'task',
    status: 'Assigned',
  },
  {
    id: 'ACT-007',
    action: 'Interview completed',
    description: 'Sneha Patel — Final Cultural & Operational Alignment Round',
    timestamp: 'Yesterday, 04:45 PM',
    type: 'interview',
    status: 'Completed',
  },
];

export const INITIAL_CHAT_MESSAGES: ChatMessage[] = [
  {
    id: 'MSG-001',
    sender: 'ai',
    text: "Hi! I'm your Virtual HR assistant. I can help you manage tasks, candidates and interviews. What would you like to accomplish today?",
    timestamp: '10:30 AM',
    quickReplies: [
      'Assign a task',
      'Schedule an interview',
      'View pending tasks',
      'Add candidate',
    ],
  },
  {
    id: 'MSG-002',
    sender: 'user',
    text: 'Schedule an interview with Rahul Sharma tomorrow at 11 AM.',
    timestamp: '10:31 AM',
  },
  {
    id: 'MSG-003',
    sender: 'ai',
    text: "Sure. I found Rahul Sharma in your candidate list (Python Developer, 94% match). What interview mode would you like?",
    timestamp: '10:31 AM',
    modeOptions: true,
  },
  {
    id: 'MSG-004',
    sender: 'user',
    text: 'Video interview',
    timestamp: '10:32 AM',
  },
  {
    id: 'MSG-005',
    sender: 'ai',
    text: "Done. I've scheduled Rahul Sharma's interview for tomorrow at 11:00 AM.",
    timestamp: '10:32 AM',
    actionCard: {
      type: 'interview_confirm',
      candidate: 'Rahul Sharma',
      position: 'Python Developer',
      date: 'Tomorrow',
      time: '11:00 AM',
      mode: 'Video',
      interviewId: 'INT-001',
    },
  },
];

export const AI_CURRENT_TASKS = [
  {
    id: 'AI-TSK-1',
    title: 'Resume Screening',
    description: 'Screening 5 remaining profiles against Python/FastAPI requirements',
    progress: 80,
    eta: '~4 mins',
    status: 'Active',
  },
  {
    id: 'AI-TSK-2',
    title: 'Interview Scheduling',
    description: 'Negotiating calendar availability with Priya Mehta for data analytics chat',
    progress: 60,
    eta: '~12 mins',
    status: 'Active',
  },
  {
    id: 'AI-TSK-3',
    title: 'Candidate Review',
    description: 'Finished scoring engineering portfolios and benchmark evaluation',
    progress: 100,
    eta: 'Completed',
    status: 'Done',
  },
];
